docs/requirements.txt
- changed PyTorch to py36
- added pip dependencies to docs/requirements.txt
=> Updated requirements.txt for readthedocs.org

.readthedocs.yml, docs/requirements.txt
Make the version the same across travis doc build, readthedoc build and the doc/requirement.txt
=> Make the version the same across travis doc build, readthedoc build and the doc/requirement.txt

forte/data/readers/multipack_sentence_reader.py, forte/data/readers/tests/conllu_ud_reader_test.py, forte/data/readers/tests/multipack_sentence_reader_test.py, forte/data/readers/tests/plaintext_reader_test.py, forte/pipeline_component.py
This PR
- Adds test for MultiPackSentenceReader
- Updates relevant docstrings
=> Add tests for MultiPackSentenceReader

examples/ner/README.md, examples/pipelines/README.md, examples/pipelines/download_models.py
This PR
- Adds a download script to download NER and SRL models from Google Cloud
- Updates Readme accordingly.
- Fixes a minor link issue NER readme.
=> Update pipeline example

forte/data/readers/tests/race_multi_choice_qa_reader_test.py, ft/onto/race_mutli_choice_qa_ontology.py
=> Changing how we store Options in Question for easier serialization

forte/data/readers/__init__.py, forte/data/readers/deserialize_reader.py, forte/data/readers/tests/deserialize_reader_test.py
This PR
- Adds a Deserialize Reader and a test case
=> Deserialize reader

.pylintrc, examples/passage_reranker/reader.py, forte/data/data_pack.py, forte/data/multi_pack.py, forte/data/readers/base_reader.py, forte/data/readers/conll03_reader.py, forte/data/readers/conllu_ud_reader.py, forte/data/readers/corpus_reader.py, forte/data/readers/deserialize_reader.py, forte/data/readers/ms_marco_passage_reader.py, forte/data/readers/multipack_sentence_reader.py, forte/data/readers/multipack_terminal_reader.py, forte/data/readers/ontonotes_reader.py, forte/data/readers/plaintext_reader.py, forte/data/readers/prodigy_reader.py, forte/data/readers/race_multi_choice_qa_reader.py, forte/data/readers/string_reader.py, forte/data/selector.py, forte/processors/base/batch_processor.py, forte/processors/base/tests/dummy_batch_processor.py, forte/processors/ner_predictor.py, forte/processors/nltk_processors.py, forte/processors/srl_predictor.py, forte/processors/text_generation_processor.py, forte/processors/writers.py
Clean too many `# pylint: disable=no-self-use` in our code.
=> Update .pylintrc file

docs/code/common.rst, docs/index.rst, forte/common/__init__.py, forte/common/const.py, forte/common/evaluation.py, forte/common/exception.py, forte/common/resources.py, forte/common/test/test_resources.py, forte/common/types.py
=> Polish the docs of common mudule

.travis.yml
=> Remove duplicated pytest

examples/pipelines/stanford_nlp_pipeline.py, examples/serialization/serialize_example.py, examples/wiki_parser/wiki_dump_parse.py, forte/data/batchers.py, forte/data/datasets/wikipedia/dbpedia_based_reader.py, forte/data/datasets/wikipedia/dbpedia_infobox_reader.py, forte/data/readers/conll03_reader.py, forte/indexers/elastic_indexer.py, forte/indexers/embedding_based_indexer.py, forte/models/srl/model.py, forte/models/srl/model_utils.py, forte/pipeline.py, forte/processors/base/index_processor.py, forte/processors/base/writers.py, forte/processors/elastic_search_index_processor.py, forte/processors/elastic_search_processor.py, forte/processors/elastic_search_query_creator.py, forte/processors/ner_predictor.py, forte/processors/nltk_processors.py, forte/processors/spacy_processors.py, forte/processors/srl_predictor.py, forte/processors/stanfordnlp_processor.py, forte/processors/tests/bert_based_query_creator_test.py, forte/processors/tests/machine_translation_processor_test.py, forte/processors/tests/nltk_processors_test.py, forte/processors/tests/stanfordnlp_processor_test.py, forte/processors/text_generation_processor.py, forte/utils/utils.py
Some of the changes to make things compatible with #140.
=> Remaining changes for HParams -> configs

setup.py
=> Adding allennlp to extras_require

forte/data/batchers.py, forte/processors/base/batch_processor.py, forte/processors/ner_predictor.py, forte/processors/srl_predictor.py, forte/processors/text_generation_processor.py, forte/utils/utils.py, tests/dummy_batch_processor.py, tests/forte/indexers/indexers_test.py, tests/forte/pipeline_test.py, tests/forte/processors/base/dummy_batch_processor_test.py, tests/forte/utils/utils_test.py
Add a few test cases for the utils of creating/getting class names from strings.
=> Add a few tests

examples/serialization/serialize_example.py, forte/data/multi_pack.py, forte/data/ontology/top.py, forte/data/readers/deserialize_reader.py, forte/pack_manager.py, tests/examples/gpt2/gpt2_test.py, tests/examples/serialization/test_serialization_example.py
Add some tests for the serialization examples.
=> Test the serialization example.

forte/data/ontology/ontology_code_generator.py, scripts/generate_ontology/__main__.py
During ontology generation, we can add a option to output a merged version of the ontology.
=> Create merged ontology if provided.

forte/version.py
This simply sync the versions.
=> Sync up versions.

examples/data_augmentation/tutorial_for_data_augmentation.ipynb
This PR adds data selector and rl-model tutorials.
=> add data selector & rl-model tutorial

docs/code/data.rst, forte/data/extractor/attribute_extractor.py, forte/data/extractor/base_extractor.py, setup.py, tests/forte/data/extractor/attribute_extractor_test.py
This PR add AttributeExtractor which inherit from BaseExtractor.
NLP tasks like NER or POS would use this class in our framework.
Test on NER dataset using this extractor is done.
=> Add attribute extractor

docs/code/data.rst, forte/data/extractor/attribute_extractor.py, forte/data/extractor/base_extractor.py, forte/data/extractor/char_extractor.py, tests/forte/data/extractor/attribute_extractor_test.py, tests/forte/data/extractor/char_extractor_test.py
This PR add another extractor CharExtractor.
NER task will need CharExtractor to extract feature.
CharExtractor is tested on CoNLL example data.
=> Add CharExtractor

docs/code/data.rst, forte/data/extractor/attribute_extractor.py, forte/data/extractor/base_extractor.py, forte/data/extractor/char_extractor.py, forte/data/extractor/seqtagging_extractor.py, forte/data/extractor/utils.py, tests/forte/data/extractor/seqtagging_extractor_test.py
This PR add SeqTagging Extractor.
Task likes NER will need this extractor.
The extractor is tested with CoNLL sample data.
=> Add SeqTagging extractor

.travis.yml, forte/indexers/__init__.py, forte/processors/base/__init__.py, forte/processors/ir/search_processor.py
This PR fixes a dependency issue on 3rd-party libraries. 
This is a temporary fix, and a full solution should be https://github.com/asyml/forte/issues/372
Some libraries are imported automatically from the module init, which makes users of Forte relying on unnecessary dependencies.
Now some imports will need to be run from full module path
Original tests are used to cover the changes.
=> Reduce unwanted dependency temporarily

forte/data/batchers.py, forte/data/readers/stave_readers.py, forte/processors/base/batch_processor.py, forte/processors/base/data_augment_processor.py, tests/forte/data/fixed_size_data_pack_batcher_with_extractor_test.py, tests/forte/data/readers/stave_reader_test.py, tests/forte/pipeline_test.py, tests/forte/processors/predictor_test.py
This PR fixes an issue where the Stave reader cannot read all projects. 
The documentation is also updated to explain the differences and gotchas.
Fix the SQLite query that finds the data packs in the all-project case.
N/A
Test not supported because our test data base have multiple projects with different names.
=> Fix a stave reader problem and update the doc.

forte/processors/base/batch_processor.py
RJQ: overwrite the flush function in the predictor (missed in previous PR)
Add one missed out overwrite function for predictor
User code do not need to change. 
Pipeline test done.
=> Predictor Patch

forte/datasets/wikipedia/dbpedia/db_utils.py, forte/datasets/wikipedia/dbpedia/dbpedia_datasets.py, tests/forte/datasets/wikipedia/dbpedia/db_utils_test.py
This PR fixes https://github.com/asyml/forte/issues/385. 
Add a catch clause when parsing the URL and return None if parsing is failed. Also updated the caller of these functions to make sure the caller knows what's happening. 
N/A
N/A
=> Fix URL parse error for ill-formatted URLs.

forte/version.py, setup.py
This PR fixes updates the new version to get ready for release
=> Update to new version

forte/common/exception.py, forte/data/base_extractor.py, forte/data/vocabulary.py, forte/processors/vocabulary_processor.py, tests/forte/data/vocabulary_test.py
This PR fixes https://github.com/asyml/forte/issues/408. 
1. Adds a few getter
2. Create a filter class that user can implement to do vocab filtering
3. Implement the filter function that takes the filter class
4. Implement a simple frequency-based filter.
=> Enrich vocabulary class

forte/processors/nlp/__init__.py, forte/processors/nlp/subword_tokenizer.py
This PR fixes #433 . 
Add a subword tokenizer as processor.
=> Add subword tokenizer

.github/workflows/main.yml
This PR fixes https://github.com/asyml/forte/issues/444. 
added dispatch workflow, when main branch changed, it will trigger forte wrapper repo.
=> add dispatch Workflow

.github/workflows/main.yml
This PR fixes https://github.com/asyml/forte/issues/444. 
Fix a problem in previous version - trigger forte-wrapper was not success.
=> reopen -disvise dispatch workflow

docs/conf.py, docs/requirements.txt, forte/data/readers/ontonotes_reader.py
This PR fixes https://github.com/asyml/forte/issues/447. 
1. Update the sphinx version to 4.0.0
2. Change an inner class name with a leading `_`, making it protected so it is not followed by the autodoc
Some new warnings raised are not identified.
=> Fix a sphinx doc error

forte/utils/tagging_scheme.py, tests/forte/utils/tagging_scheme_test.py
This PR fixes https://github.com/asyml/forte/issues/479. 
add a bio tagging merge function.
=> add a bio tagging merge function

HISTORY.rst, forte/version.py, setup.py
This PR bumps the version of Forte only [skip ci].
=> [skip ci] Bump forte version.

forte/version.py, setup.py
This PR update forte version to `0.1.1.post1`. 
Describe what are the changes, and how they solve the problem.
=> Update version to 0.1.1.post1

examples/wiki_parser/wiki_dump_parse.py, forte/datasets/wikipedia/dbpedia/dbpedia_datasets.py, forte/processors/base/writers.py, forte/processors/writers.py, tests/forte/datasets/wikipedia/dbpedia/dbpedia_datasets_test.py
This PR fixes some problems in wikipedia writing problems. 
Make the wiki writer use the input index paths, to write the data into the original data pack.
Only affect the Wikipedia reader.
=> Slight updates to wikipedia

forte/processors/base/base_processor.py
This PR addresses part of the issues in  #498, which adapts only one file change from #499.
Remove the unused selector configs to avoid confusion.
N/A
=> Remove unused selector config

forte/data/batchers.py, forte/processors/base/batch_processor.py, forte/processors/nlp/ner_predictor.py, forte/processors/nlp/srl_predictor.py, tests/forte/pipeline_test.py, tests/forte/processors/stave_processor_test.py, tests/forte/processors/timeprofiling_test.py
This PR fixes https://github.com/asyml/forte/issues/523. 
1. Move `FixedSizeDataPackBatcher` to `FixedSizeDataPackBatcher`, which uses request interface
2. Leave `FixedSizeDataPackBatcher` as an abstract class that expose a un-implemented `_get_instance` function
=> Fix a few more batcher interface.

forte/processors/data_augment/README.md
This PR adds to the README the newly implemented typo augment generator.
=> Adding Typo replacement README

setup.py
This PR bumps the version of smart-open (reduce the version strictness)
=> small version

docs/requirements.txt, forte/pipeline.py, requirements.txt
This PR is a follow-up to https://github.com/asyml/forte/pull/705. 
1. Update `requirements.txt` to sync up with `setup.py`.
2. Move `pandantic` dependency together with `fastapi`.
=> Relax the version further

.github/workflows/pypi.yml, .github/workflows/testpypi.yml
This PR fixes [the workflow error in testpypi.yml](https://github.com/asyml/forte/actions/runs/2234707162/workflow).
=> Fix invalid pypi workflow

examples/bounding_box/check_overlap.py, forte/data/data_pack.py, forte/data/ontology/top.py, tests/forte/grids_test.py, tests/forte/image_annotation_test.py
This PR fixes https://github.com/asyml/forte/issues/802. 
* create ontologies ImageAnnotation -> Region -> Box -> BoundingBox
* implement box function check overlapping and compute iou
* create an example of checking overlapping and compute iou
=> Bounding box

.github/workflows/testpypi.yml, forte/version.py, tests/forte/data/data_store_test.py
* Update workflow name of `testpypi.yml` to `TESTPYPI`
* Bump version to `0.3.0.dev2`
* Fix a bug in data_store_test.py
=> Bump version to 0.3.0.dev2

.github/workflows/main.yml, forte/version.py, setup.py
Bump version to `0.3.0.dev3`
Set an upper bound for `transformers` version.
=> Bump version to 0.3.0.dev3

README.md, docs/requirements.txt, forte/data/ontology/ontology_code_generator.py, setup.py
This PR fixes #927 . 
Describe what are the changes, and how they solve the problem.
Change versions and remove type ignore
Type checking error might arise
All the testcases as running previously
=> 927 Github workflow failing 
