asyml/forte

.codecov.yml, .travis.yml
This PR
- Adds YAML for code coverage. We can use this file to configure our coverage on https://codecov.io/
- Uses `pytest` to generate coverage report instead of `unittest`. There was a bug in the discover pattern used for `unittest`. Hence choosing `pytest` for simplicity.
=> Coverage Settings

forte/processors/stanfordnlp_processor.py
This PR
- Fixed a bug. We now get the token from `add_or_get_entry()` before appending to `tokens`. This fixes the issue when the datapack already contains the tokens, we would like to operate on the existing token.
=> Fix a bug in StanfordProcessor

forte/processors/ner_predictor.py
This PR fixes
- An issue while loading model weights. We now use `torch.load` instead of `pickle.load` to load weights.
=> Use torch.load and map_location to load the weights

examples/ner/ner_vocab_processor.py, forte/__init__.py, forte/base_pipeline.py, forte/data/readers/base_reader.py, forte/data/readers/multipack_sentence_reader.py, forte/data/readers/tests/multipack_sentence_reader_test.py, forte/pipeline_test.py, forte/processors/base/base_processor.py, forte/processors/base/tests/dummy_batch_processor.py, forte/processors/base/tests/dummy_batch_processor_test.py, forte/processors/bert_based_query_creator.py, forte/processors/nltk_processors.py, forte/processors/spacy_processors.py, forte/processors/tests/bert_based_query_creator_test.py, forte/processors/tests/nltk_processors_test.py, forte/processors/tests/spacy_processors_test.py
=> Pipeline interface refactor

examples/content_rewriter/prepare_pipeline.py, examples/content_rewriter/table_inputs/table_Cocum.json, examples/content_rewriter/table_inputs/table_Loch_Fyne.json, examples/content_rewriter/table_inputs/table_The_Mill.json, examples/content_rewriter/table_inputs/table_The_Vaults.json
This PR adds some instruction into the content rewriter data.
The content rewriter datapack only contains the table, which is not clear to the users what to do. I added the instruction there.
N/A
This example is currently not tested.
=> Add instructions to examples so they can be shown on webpages.

forte/data/ontology/code_generation_objects.py, forte/data/ontology/ontology_code_generator.py, forte/ontology_specs/base_ontology.json, ft/onto/base_ontology.py, tests/forte/data/ontology/test_outputs/ft/onto/base_ontology.py, tests/forte/data/ontology/test_outputs/ft/onto/example_ontology.py, tests/forte/data/ontology/test_specs/base_ontology.json
This PR fixes https://github.com/asyml/forte/issues/233. 
The generator has the `self_ref` functionalities, but it is removed in one of the early commits. This fix reverts it back.
Added such self-referencing types in two different test ontology files.
=> Fix the problem of self referencing during code generation.

examples/Cliner/reader.py, examples/content_rewriter/reader.py, examples/passage_ranker/reader.py, forte/data/datasets/wikipedia/dbpedia_based_reader.py, forte/data/readers/ag_news_reader.py, forte/data/readers/base_reader.py, forte/data/readers/conll03_reader.py, forte/data/readers/conllu_ud_reader.py, forte/data/readers/html_reader.py, forte/data/readers/largemovie_reader.py, forte/data/readers/ms_marco_passage_reader.py, forte/data/readers/multipack_sentence_reader.py, forte/data/readers/multipack_terminal_reader.py, forte/data/readers/ontonotes_reader.py, forte/data/readers/openie_reader.py, forte/data/readers/plaintext_reader.py, forte/data/readers/prodigy_reader.py, forte/data/readers/race_multi_choice_qa_reader.py, forte/data/readers/sem_eval_task8_reader.py, forte/data/readers/sst2_reader.py, forte/data/readers/string_reader.py, forte/processors/base/base_processor.py, forte/processors/base/batch_processor.py, forte/processors/base/pack_processor.py, tests/forte/data/entry_data_structures_test.py, tests/forte/pipeline_test.py
This PR removes `new_pack()` function from processors.
The `new_pack` function is required when some dependencies
are required between packs, so we need a manager to maintain
them, now that we use uuid, we no longer need this function.
Removing the `new_pack` function from the base classes and
all the calls to it.
Other projects that use `new_pack` may get affected.
Existing test cases should cover this PR.
=> Removing new_pack entirely.

data_samples/ontonotes/nested_spans/abc_0009.gold_conll, forte/data/readers/ontonotes_reader.py, tests/forte/data/data_pack_test.py, tests/forte/data/readers/ontonotes_reader_test.py
Original, there are two issues for [OntonotesReader](https://github.com/asyml/forte/blob/master/forte/data/readers/ontonotes_reader.py):
* The `Predicate Argument` span start/end detection is not currect for nested span cases like `(ARG1(R-ARG2*)`
* There could be multiple documents in a single dataset file. However, the reader will only parse the first document in the file and ignore all subsequent documents in this file.
Regarding the first issue, a workaround is used to ignore all inner spans.
Regarding the second issue, now each document in a file will be parsed into a single `datapack`.
N/A
Will add unit testing for those two issue cases.
=> Update predicate argument span start/end detection and read multiple documents in one file - Ontonotes Reader

data_samples/base_reader_test/0.txt, data_samples/base_reader_test/1.txt, data_samples/base_reader_test/2.txt, forte/data/readers/base_reader.py, tests/forte/data/readers/base_reader_test.py
This PR fixes #315.
Track parsed data pack in side reader and retrieve those data packs instead of re-parsing from disk file when the `iter` method is called the second time.
Default is do not cache in memory so it should have no side-effect for current readers.
N/A
=> Support memory cached data pack inside reader

forte/data/readers/ontonotes_reader.py
This PR fixes the issue that `OntonotesReader` does not accept `BaseReader` level init arguments. And this is partially related to this [issue](https://github.com/asyml/forte/issues/334)
Move initialization logic to `initialize` method. And move default `column format` to `default_config`.
Another PR (main train SRL which will be raised soon) will use this feature.
The change should not affect current unit testings
=> Move column format logic to `initialize` method

forte/data/base_pack.py, forte/data/data_pack.py, forte/data/data_utils.py, forte/data/datasets/wikipedia/dbpedia_infobox_reader.py, forte/data/multi_pack.py, forte/data/readers/base_reader.py, forte/data/readers/deserialize_reader.py, forte/data/readers/stave_readers.py, forte/processors/base/data_selector_for_da.py
This PR moves the deserailize from `data_utils` to Pack classes.
The deserialize function can be called directly from the Pack classes as class methods. The reasons are:
1. It is more intuitive to do deserialization from the individual classes.
2. The typing can be more clear by doing this.
Previous tests on the deserialization should cover this.
=> Move deserialize into Pack classes

forte/data/extractor/base_extractor.py, forte/data/vocabulary.py, tests/forte/data/extractor/base_extractor_test.py, tests/forte/data/vocabulary_test.py
use `__getstate__` and `__setstate__` to save vocabulary instead of `state` and `from_state` function.
The way to save vocabulary will be changed. After this PR, users can use pickle to save vocabulary directly.
Pickle load and dump is tested.
=> [vocab/extractor] use pickle to dump and load Vocabulary and Extractor

forte/data/extractor/base_extractor.py
The way of checking whether vocabulary is not robust.
Thanks for @ziqian98 finding this bug.
=> Fix bug on None in the BaseExtractor

forte/models/srl/model.py, forte/models/srl/model_utils.py, forte/processors/srl_predictor.py
This PR fixes https://github.com/asyml/forte/issues/364. 
There are a few changes in the API causing the SRL example to fail:
1. The `Span` object now only takes native Python int, so we need to convert before creating Span now.
2. Forte's default parameter function is named `default_config` but the Texar one is named `default_hparam`. For any models that extend the texar module, we should correctly use `default_hparam`, otherwise the system will not find the correct config. 
Code changes are only inside the SRL model.
No new tests are not added yet.
=> Fixing SRL hparam errors

forte/pipeline.py
This PR fixes https://github.com/asyml/forte/issues/359. 
In principle, this is not exactly a builder pattern, but this is what this issue is about.
With the new change, you can try the following one-liner. 
`Pipeline().set_reader(StringReader()).add(LowerCaserProcessor()).initialize().process('This is an example').text`
Return the `Pipeline` itself at several key building stage, including `set_reader`, `add`(processor) and `initialize`.
=> Allow chaining the processors in one-liners

forte/ontology_specs/base_ontology.json, ft/onto/base_ontology.py
This PR modified subword ontology and regenerated base_ontology.py
base_ontology.py should be automatically generated. However, someone manually modified the subword ontology, and caused an issue while using it. This PR added 'is_first_segment' as an attribute to subword ontology in Json file and regenerated the base_ontology.py by running 'generate_ontology' command.
=> Regenerate subword ontology

examples/wiki_parser/wiki_dump_parse.py, forte/datasets/wikipedia/dbpedia/dbpedia_datasets.py
This PR fixes the Wikipedia reading example.
The original example will ignore articles that do not have "properties" or "info box literals". This is not desired since many pages fall into this category. This fix read the data in place, which means it will add properties to the existing page instead of creating a new directory of articles. This makes the dataset complete.
Examples are currently not tested.
=> Make the reader example read the complete data 

README.md, docs/requirements.txt
Doc requirements need to be retained to make it run on read-the-docs
Some dependencies are removed from docs/requirements.txt, but that will make read-the-doc fail because the site only reads doc/requirements.txt. This PR revert back that change.
=> Fix doc runs

forte/processors/ir/elastic_search_processor.py
This PR fixes [#402]. 
Check query.value instead of query which is not a Dict.
None
Successfully ran pipeline connecting ElasticSearchQueryCreator and ElasticSearchProcessor
Closes #402
=> fix instance check in ElasticSearchProcessor

forte/data/ontology/code_generation_exceptions.py, forte/data/ontology/ontology_code_generator.py, forte/ontology_specs/race_qa.json, forte/ontology_specs/wikipedia.json, tests/forte/data/ontology/ontology_code_generator_test.py, tests/forte/data/ontology/test_specs/test_invalid_attr_name.json, tests/forte/data/ontology/test_specs/test_invalid_entry_name.json
This PR fixes https://github.com/asyml/forte/issues/406 
Check for the names in the entry name and attribute to see if they are identifiers. Exceptions will be thrown if not.
N/A
Added two test cases where the identifiers are wrong, and throw relevant exceptions.
=> Throw exceptions when the ontology definition contains invalid identifiers

setup.py
This PR fixes the problem where examples, tests and scripts are included in the published package.
Change the exclude in `find_packages` command slightly to include a `*`, which now successfully exclude the folders.
=> Fix setup.py including example and test folders.

forte/data/base_reader.py, forte/data/data_pack.py, forte/data/selector.py, forte/pipeline.py, forte/pipeline_component.py, tests/forte/pipeline_test.py
This PR fixes https://github.com/asyml/forte/issues/410. 
1. Add a flag for each `PipelineComponent` marking the initialization status.
2. When the pipeline is initializing, it will check whether the flag is True. It will skip initializing the processor if the flag is True.
A reuse-processor test is added. The testing processor will record the number of times it gets initialized. And the number should be 1.
=> Do not initialize the same processor instance multiple times

forte/data/vocabulary.py
This PR fixes https://github.com/asyml/forte/issues/429. 
1. Added two values `pad_value` and `unk_value` in `__init__`, apply them when adding the special elements.
2. Add relevant docstring.
=> Allow setting the special representation when initializing the vocabulary.

forte/processors/misc/__init__.py, forte/processors/misc/delete_overlap_entries.py
This PR fixes https://github.com/asyml/forte/issues/449. 
Move delete_overlap_entry processor from composing_info_system repo to Forte misc processors (forte/processors/misc).
=> Move delete_overlap_entry processor to Forte

forte/pipeline.py, forte/processors/misc/remote_processor.py, tests/forte/processors/remote_processor_test.py
This PR is an update to #476. 
- pipeline.py
- User can assign a name to pipeline service by calling `Pipeline().serve(name="name")` or `forte.serve(pl_path="pl_path", name="name")` 
- Add a new page `\records` in FastAPI app which will return a collection of records from all components in the pipeline.
- remote_processor.py
- User can now configure `RemoteProcessor` to validate the remote service by adding `do_validation`, `expected_name` and `expected_records` field.
```python
pipeline.add(
RemoteProcessor,
config={
"do_validation": True,
"expected_name": service_name,
"expected_records": json.dumps(
{"Token": ["1", "2"], "Document": ["2"]}
),
},
)
```
- remote_processor_test.py
- Add test case for service name and records checking. 
`remote_processor_test.py` is updated to test …
=> Add service validation

forte/processors/stave/stave_processor.py, tests/forte/data/ontology/test_specs/test_project_configuration.json, tests/forte/data/ontology/test_specs/test_stave_ontology.json, tests/forte/processors/stave_processor_test.py
This PR fixes #489 . 
- Add a fixed ontology `test_specs/test_stave_ontology.json` that is only meant for test of project config generation. This should not be changed in future updates.
- Based on `test_stave_ontology.json`, `test_project_configuration.json` is regenerated from the frontend page when adding a new project in Stave. The fixed ontology goes through [createDefaultConfig](https://github.com/asyml/stave/blob/d42c3816a3e0ec9d4eb6cb0c9d6fb48ac93a5861/src/app/pages/Projects.tsx#L140) to create a new version of default project configuration.
- `stave_processor.py` is updated to reflect [a recent change](https://github.com/asyml/stave/commit/c09ab5d987109dd1c45459da08a2582fcea85877#) in [createDefaultConfig](https://github.com/asyml/stave/blob/d42c3816a3e0ec9d4eb6cb0c9d6fb48ac93a586 …
=> Use fixed ontology to test StaveProcessor

.github/workflows/main.yml, setup.py
This PR added support for python3.9. 
- `setup.py`
- Update `numpy` version to `>=1.16.6`
- Update `typed-ast` version to `>=1.4.3`
Potential dependency issues after updating `numpy` and `typed-ast` to higher version.
`.github/workflows/main.yml` is updated to test python3.8 and 3.9:
- Add two tests for python3.8:
- python-version: [ 3.8 ]
- torch-version: [ 1.7.1, 1.8.1 ]
- tensorflow-version: [ 2.2.0 ]
- Add two tests for python3.9:
- python-version: [ 3.9 ]
- torch-version: [ 1.7.1, 1.8.1 ]
- tensorflow-version: [ 2.5.0 ]
=> Update to support python3.9

tests/forte/data/ontology/ontology_code_generator_test.py, tests/forte/data/ontology/test_outputs/ft/onto/test_top_attribute.py, tests/forte/data/ontology/test_specs/test_top_attribute.json
This PR adds some test cases for ontology generation where top entries are used as attributes. 
Add the test ontology and the expected output, where the top attributes such as `top.Query`
are used as the attribute.
Only added the test cases.
=> Add test cases for top entries as part of the attributes.

setup.py
This PR updates stave version requirement from `==0.0.1.dev12` to `>=0.0.1.dev12`. 
Describe what are the changes, and how they solve the problem.
=> Update version requirement of stave

forte/common/configurable.py, forte/data/multi_pack.py, forte/data/selector.py, tests/forte/data/multi_pack_test.py, tests/forte/data/selector_test.py
This PR fixes https://github.com/asyml/forte/issues/538. 
1. Make `SinglePackSelector` to control the basic selection flow, and the sub classes only return a boolean from `will_select` function
2. The default configs are added to the `SinglePackSelector`.
3. Some changes are made to make sure the configs are correctly inherited between classes. 
=> Make some base selector, such as reverse selection

forte/data/caster.py, forte/data/multi_pack.py, forte/data/ontology/ontology_code_generator.py, forte/data/ontology/top.py, forte/pipeline.py, forte/processors/base/pack_processor.py, forte/processors/base/writers.py
This PR fixes https://github.com/asyml/forte/issues/542
1. Allow `caster` to assign a name to multipack automatically
2. When creating new data pack in multi packs, allow assigning a name
3. Add clear exception when constraint_type is not set in ontology code generator
4. Do not query `selector_config` when it is None.
5. Remove unused function `new_data_pack` in pack_processor
6. Check for `output_dir` in writers.
=> Fixing a few configuration bugs

forte/data/base_reader.py, forte/data/caster.py, forte/data/readers/misc_readers.py, tests/forte/data/datapack_type_infer_test.py
This PR fixes [Issue #551](https://github.com/asyml/forte/issues/551).
- Reader: change `pack_type` from `property` to `staticmethod`.
- Caster: add static method `input_pack_type` and `output_pack_type`.
- Reader: `pack_type` now should be used as function call, _e.g._ `Reader.pack_type()` instead of `Reader.pack_type`.
- Caster: now it is able to infer input/output data type by `Caster.input_pack_type()`/`Caster.output_pack_type()`.
None
=> added static methods to infer pack type

forte/processors/data_augment/algorithms/eda_processors.py, forte/processors/data_augment/algorithms/word_splitting_processor.py, forte/processors/data_augment/base_data_augment_processor.py, tests/forte/processors/base/data_augment_replacement_processor_test.py, tests/forte/processors/data_augment/algorithms/back_translation_augmenter_test.py, tests/forte/processors/data_augment/algorithms/embedding_similarity_replacement_op_test.py, tests/forte/processors/data_augment/algorithms/word_splitting_processor_test.py
Removal of the `type` parameter in configs of data augmentation processors.
This PR will help reduce confusion regarding the `type=""` that appeared in DA processors until now.
Tested the working of these changes on all DA methods that inherited the `base_data_augment_processor`.
=> Type Key Removal in Configs

examples/visualize/README.md, forte/pipeline.py
This PR fixes #557 
- Add documentation to the visualize example
- Instruction of how to save the generated visualization to Stave backend
- Fix some small issues in `pipeline.py`
- Add `logger.error` in `_process_with_component()` to prevent the exception from being suppressed by `uvicorn` in remote service.
- Add `hasattr` checking in `_remote_service_app.get_records()` and `_remote_service_app.get_expectation()`.
=> Fix pipeline.py and add documentation to the visualize example

CONTRIBUTING.md, examples/blog_post_examples/pytorch_ecosystem.py, examples/chatbot/chatbot_example.py, examples/clinical_pipeline/clinical_processing_pipeline.py, examples/data_augmentation/data_select/data_select_and_augment_example.py, examples/pipelines/process_dataset_example.py, examples/pipelines/process_string_example.py, examples/serialization/serialize_example.py
This PR fixes https://github.com/asyml/forte/issues/565. 
- Replaced all examples which contain `import forte.nltk` to `import fortex.nltk`.
=> Replaced incompatible package names for fortex.nltk

docs/data_pack.md, docs/index.rst, forte/data/data_pack.py, tests/forte/data/audio_annotation_test.py
This PR fixes #602 . 
Add `AudioAnnotation` support to `DataPack.build_coverage_for`:
- class `DataIndex`: `have_overlap`, `build_coverage_index`, `get_covered`, `coverage_index`
- Most changes are related to docstring and type annotations. Add logics related to type checking in `have_overlap`.
- class `DataPack`: `build_coverage_for`, `covers`, `get`, `iter_in_range`
- Add more details of how to build a coverage index in the docstring of `get`
- Refactor `iter_in_range` to support binary search on audio annotations
- A tutorial for DataPack usage is created. Right now it only includes guidelines about building coverage index.
`audio_annotation_test.py` is extended to include unit tests regarding the coverage index update.
=> Add AudioAnnotation support to build_coverage_for

examples/clinical_pipeline/clinical_processing_pipeline.py, examples/clinical_pipeline/utterance_searcher.py, examples/data_augmentation/data_select/data_select_index_pipeline.py, examples/passage_ranker/create_index.py, examples/passage_ranker/indexer_reranker_eval_pipeline.py, examples/passage_ranker/indexer_reranker_inference_pipeline.py, examples/visualize/visualize.py
This PR fixes https://github.com/asyml/forte/issues/623
Import statements for packages like forte.huggingface, forte.elastic, etc were repaired
eg, 
`import forte.hugginface` changed to `import forte.huggingface`
`import forte.elastic` changed to `import forte.elastic`
Should allow executing some of our examples without throwing `ModuleNotFoundError`
=> Import statements repaired for some examples

.pre-commit-config.yaml, CONTRIBUTING.md
This PR fixes https://github.com/asyml/forte/issues/651. 
* Add a pre-commit-hook configuration file with black formatting check.
* Add pre-commit-hook dependency requirement in `requirements.txt` file.
=> add pre commit hooks for checking black formatting

setup.py
This PR fixes #658 . 
Append 'forte' to `include` and remove the `exclude` argument for `find_namespace_packages` in setup.py.
Go through the steps in `To Reproduce` section in #658 and see if the bug still exists.
=> Fix package not found issue 

forte/data/data_utils.py
This PR fixes #672. #672 might be caused by a recent update in Google API. Previously, when google drive responds with a warning page, `maybe_download()` is able to retrieve token info from a key starting with `"download_warning"` stored in cookies of the response. The token will be used to prepare a second request, which will download the actual large file (for details, refer to https://stackoverflow.com/a/39225039). However, recently we cannot find the token from the cookies, thus it fails to recognize the warning page.
We propose a workaround based on this [post](https://stackoverflow.com/a/48238689), which extracts the token from a `"confirm=([0-9A-Za-z_]+)"` pattern found in the warning page.
Go through the steps in `To Reproduce` section from #672 and see if the bug still exists. …
=> Fix maybe_download issue

forte/data/data_utils.py, tests/forte/data/data_utils_test.py
This PR fixes a silent failure of `maybe_download` when getting 403 response from download requests to Google Drive, which is now blocking [some of the CI testing]( https://github.com/asyml/forte/runs/5636898988?check_suite_focus=true#step:15:140). The reason of 403 response might be related to the rate limit that Google Drive imposes (refer to [here](https://developers.google.com/drive/api/guides/handle-errors) for details) and a temporary solution is to retry a few times or simply ignore the error if it's inside a unit test.
- data_utils.py: Previously `_download_from_google_drive()` does not handle scenarios where the status code of response is not 200, in which case the program may fail silently. Hence we will check the status code and resend requests when `status_code!=200`. Raise a …
=> Handle 403 response from google drive download requests

forte/data/data_utils.py
Add `num_gdrive_retries` to `maybe_download()` to specify the number of retries of download requests to Google Drive
=> Add `num_gdrive_retries` to `maybe_download()`

docs/requirements.txt
This PR fixes https://github.com/asyml/forte/issues/699. 
The latest update on `jinja2==3.1.0` removed `environmentfilter` which is needed.
* Add restrictions on `jinja2` version to `<=3.0.3`
=> jinja2 3.1.0 is incompatible so downgrade is needed

forte/processors/misc/remote_processor.py
Remove `import fastapi` from `remote_processor.py` so that users can import other processor from `forte/processors/misc` without installing `fastapi`.
=> Remove import fastapi from remote_processor.py

.github/workflows/testpypi.yml, setup.py
Split `pypi.yml` into two workflows:
* `testpypi.yml`: Triggered by a new tag/release or manually.
* `pypi.yml`: Can only be triggered mannually.
Single-sourcing the package version:
* `setup.py` will read forte version from `forte/version.py`.
* reference: https://packaging.python.org/en/latest/guides/single-sourcing-package-version/
A new release/tag will no longer automatically upload the package to PyPi. It will only push the repo to TestPyPi.
This PR can be tested by updating `version.py` and then triggering the testpypi/pypi workflow. We can check the version of the package uploaded to testpypi/pypi.
=> Split the pypi workflow and single-source the version

setup.py
This PR fixes https://github.com/asyml/forte/issues/776. 
* add a version upper bound `0.75.2` for fastapi 
* it will unblock the CI test.
=> add version upper bound <=0.75.2 to fastapi

forte/data/data_store.py, tests/forte/data/data_store_test.py
This PR fixes #786. 
* In `DataStore._new_annotaion()`, `DataStore._new_link()` and `DataStore._new_group()`,  each attribute will be initialized based on its typing annotation.
* FDict, Dict -> {}
* FList, List -> []
* other types (premitives, Union, NoneType, etc.) -> None
`test_add_annotation_raw()` is updated to validate this new initialization behavior.
=> Initialize new entry attribute list with default values

forte/data/data_store.py, tests/forte/data/data_store_test.py
This PR fixes #774. 
* Provide an option called `allow_duplicate` to specify whether to add identical entries into DataPack. If it's set to `False`, then  `add_annnotation_raw` should just return the existing entry if a duplicate is found.
* Fix incorrect attribute types in setup according to updates from #796.
`test_add_annotation_raw` is updated to test duplicate checking
=> Check duplicates when adding new annotation to DataStore

forte/version.py
`forte` version is upgraded to "0.3.0.dev1".
`PACK_VERSION` and `PACK_ID_COMPATIBLE_VERSION ` are set to `0.0.2`.
=> Bump minor version and pack version

README.md
This PR fixes #824. 
Add one line to define the token_entries:
```python
token_entries = input_pack.get(Token)
```
Little change in README.md
With this change, the python code in Quick Start Guide is runnable.
=> Bug fix of the NameError where token_entries is not defined

.github/workflows/main.yml, README.md
This PR fixes https://github.com/asyml/forte/issues/829. 
* change `TerminalReader` to `StringReader`
* fixed the issue https://github.com/asyml/forte/issues/829#issuecomment-1150472115
* add package `mkcodes` that convert markdown code into python script
* generate python script based on latest README, test it and remove it after testing 
=> Doc test readme

forte/data/base_store.py, forte/data/data_pack.py, forte/data/data_store.py, forte/data/entry_converter.py, tests/forte/data/data_store_test.py
This PR fixes #837 . 
In this PR, we created the `add_entry_raw` method which acts as a single interface for adding all different types pf entries. ie, `Annotation`, `AudioAnnotation`, `Group`, `Link`, `ImageAnnotation` and `Generics`. This is done by introducing the argument `attribute_data` which acts as a common medium for all types of entries to be created in the same way. The type of values being passed in `attribute_data` is dependent on the type of entries. (Currently, the length of the `attribute_data` list is **2** as those are the number of attributes required currently.
Through this PR, the need for having separate `add_***_raw` method is gone and we can use just one method to add different types of entries.
The `data_store_test.py` file was modified to use the new …
=> Add Entry Raw Method

setup.py
This PR fixes https://github.com/asyml/forte/issues/851. 
Added `enum34` in `setup.py`.
=> Make sure enum is part of the setup.py

CHANGELOG.md, HISTORY.rst, forte/data/multi_pack.py, forte/version.py
This PR fixes https://github.com/asyml/forte/issues/853. 
1. Fix the multipack version-check version
2. Add documentation in `version.py` and update `history.rst` to record the data pack version compatibility
=> Update data pack version documentation and a multipack check bug

forte/data/ontology/code_generation_objects.py, forte/data/ontology/ontology_code_generator.py, tests/forte/data/ontology/ontology_code_generator_test.py, tests/forte/data/ontology/test_specs/test_self_reference.json
This PR fixes https://github.com/asyml/forte/issues/862. 
Reorder the generation steps can solve the problem, if we make sure we parse the entry name before the arguments, the warning won't happen for us.
This may change the code generation steps slightly, but if all the code gen tests pass, then it shouldn't introduce any influences.
Add a test to capture if the warning does not exist when the attribute type is the same as the entry type.
=> Remove a warning from code gen that occurs frequently

forte/data/readers/html_reader.py, tests/forte/data/readers/html_reader_test.py
This PR fixes https://github.com/asyml/forte/issues/871. 
1. move `collect_span` after all the handling of `k` value, which makes it larger than 0 (should be larger than i). 
2. Also make sure `k > i` before calling `collect_span`
The output of html_reader is likely to change a bit on wrong tags and some whitespaces.
1. Added the test case with incomplete tags
=> Fix a simple html reader bug

docs/notebook_tutorial/tutorial_MT_with_forte.ipynb, examples/bounding_box/check_overlap.py, forte/data/ontology/top.py, tests/forte/image_annotation_test.py
This PR fixes  https://github.com/asyml/forte/issues/878.
* The default Box init method: height and width and center -> init Box by top left point and bottom right point
* move init by  height &  width & center to a classmethod
It can simplify the Box API and enable two ways of initialization.
Tested wrong box shape and wrong x/y coordinates of top left point and bottom right point.
=> Ontology Box init by top left point and bottom right point

forte/data/data_store.py, forte/data/ontology/ontology_code_generator.py
This PR fixes https://github.com/asyml/forte/issues/923. 
Related test code were added to determine details related exception (including statistics comparison with earlier code). The data shows the newly added exception handling code impact the performance most while the difference in dictionary access is insignificant so only the exception handling code is changed.   
Since no other place than the exception handling part is changed, the impact to other code is minimum, and the performance issue can be resolved (speed restored to previous level).
Usual unit tests and profiling tests.
=> Fix performance impact of exception handling in _is_annotation_tid()
